backend:
  name: git-gateway
  repo: mikeour/ruse-kitchen-website
  branch: master

media_folder: static/assets

site_url: https://rusekitchen.com
display_url: https://rusekitchen.com

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: text }
      - label: "Where Page"
        name: "where"
        file: "content/where.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: text }
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: text }

  - label: "Menu Items"
    name: "menu"
    label_singular: "Menu Item"
    description: >
      Create menu items here! Each listing here will add a new item to your menu page.
    folder: "content/menu-items"
    create: true
    fields:
      - {
          label: "Item Name",
          name: "title",
          hint: "What's it called?",
          widget: "string",
        }
      - {
          label: "Item Description",
          name: "description",
          widget: "string",
          hint: "What's in it?",
        }
      - {
          label: "Item Position",
          name: "position",
          widget: "number",
          required: false,
        }

  - label: "Partners"
    name: "partners"
    label_singular: "Partner"
    description: >
      Create partners here! Each item here will add a new partner to your partner page.
    folder: "content/partners"
    create: true
    identifier_field: name
    fields:
      - {
          label: "Position",
          name: "position",
          widget: "number",
          required: false,
          hint: "Where this will be positioned in order, the higher the number the later it will be.",
        }
      - {
          label: "Partner Name",
          name: "name",
          widget: "string",
          hint: "The name of the partner!",
        }
      - {
          label: "Partner Website",
          name: "url",
          widget: "string",
          required: false,
          hint: "The website of the partner you'd like to link to!",
        }
      - {
          label: "Address",
          name: "address",
          widget: "string",
          required: false,
          hint: "Partner's location",
        }
      - {
          label: "Phone Number",
          name: "phone",
          widget: "string",
          required: false,
          hint: "Their phone number",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
          hint: "A sentence or two talking about your affiliation. eg: Pure Health Foods is a local health food store where you can purchase our pre-packaged meat. Here, we sell our plant-based gyro, spicy Italian sausage and our charbroiled steak to take home!",
        }

  - label: "Pop Up Events"
    name: "popups"
    label_singular: "Pop Up Event"
    description: >
      Create pop-up events here! Each event here will add a new event to your pop-up page.
    folder: "content/pop-up-events"
    create: true
    fields:
      - {
          label: "Event Position",
          name: "position",
          widget: "number",
          required: false,
          hint: "Where this will be positioned in order, the higher the number the later it will be.",
        }
      - {
          label: "Event Name",
          name: "title",
          widget: "string",
          hint: "eg: Floyd Lamb Park ",
        }
      - {
          label: "Event Day",
          name: "day",
          widget: "string",
          required: false,
          hint: "eg: Friday",
        }
      - {
          label: "Event Date",
          name: "date",
          widget: "string",
          required: false,
          hint: "eg: September 21",
        }
      - {
          label: "Event Address",
          name: "address",
          widget: "string",
          required: false,
          hint: "eg: 1234 Sunset Road",
        }
      - {
          label: "Event Time",
          name: "time",
          widget: "string",
          required: false,
          hint: "eg: 12pm - 4pm",
        }
      - {
          label: "Event Description",
          name: "description",
          widget: "markdown",
          required: false,
          hint: "Whatever important information you wanna include!",
        }
      - {
          label: "Event Map URL",
          name: "map_url",
          widget: "string",
          required: false,
          hint: "Just a normal Google Maps link!",
        }

  - label: "Order Items"
    name: "orders"
    label_singular: "Order Item"
    description: >
      Create order items here! Each item here will add a new item to your order page.
    folder: "content/order-items"
    create: true
    fields:
      - {
          label: "Item Name",
          name: "title",
          widget: "string",
          hint: "Name of the item in database",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
          hint: "Item description, eg: Plant based gyro with harissa, tzatiziki, marinated cucumbers, tomatoes and onions all on a folded pita",
        }
      - {
          label: "Price",
          name: "price",
          widget: "string",
          required: false,
          hint: "Enter a number",
        }
      - {
          label: "Serves",
          name: "serves",
          widget: "string",
          required: false,
          hint: "Enter a number",
        }
      - {
          label: "Position",
          name: "position",
          widget: "string",
          required: false,
          hint: "Where you'd like this item positioned",
        }
