backend:
  name: git-gateway
  repo: mikeour/ruse-kitchen-website
  branch: master

media_folder: static/assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: text }
      - label: "Where Page"
        name: "where"
        file: "content/where.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: text }
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: text }

  - label: "Menu Items"
    name: "menu"
    label_singular: "Menu Item"
    description: >
      Create menu items here! Each listing here will add a new item to your menu page.
    folder: "content/menu-items"
    create: true
    fields:
      - { label: "Item Name", name: "title", widget: "string" }
      - { label: "Item Description", name: "description", widget: "string" }
      - { label: "Item Position", name: "position", widget: "number" }

  - label: "Pop Up Events"
    name: "popups"
    label_singular: "Pop Up Event"
    description: >
      Create pop-up events here! Each event here will add a new event to your pop-up page.
    folder: "content/pop-up-events"
    create: true
    fields:
      - {
          label: "Event Position",
          name: "position",
          widget: "number",
          hint: "Where this will be positioned in order, the higher the number the later it will be.",
        }
      - {
          label: "Event Name",
          name: "title",
          widget: "string",
          hint: "eg: Floyd Lamb Park ",
        }
      - {
          label: "Event Day",
          name: "day",
          widget: "string",
          hint: "eg: Friday",
        }
      - {
          label: "Event Date",
          name: "date",
          widget: "string",
          hint: "eg: September 21",
        }
      - {
          label: "Event Address",
          name: "address",
          widget: "string",
          hint: "eg: 1234 Sunset Road",
        }
      - {
          label: "Event Time",
          name: "time",
          widget: "string",
          hint: "eg: 12pm - 4pm",
        }
      - {
          label: "Event Description",
          name: "description",
          widget: "markdown",
          hint: "Whatever important information you wanna include! Written in Markdown",
        }
      - {
          label: "Event Map URL",
          name: "map_url",
          widget: "string",
          hint: "Just a normal Google Maps link!",
        }

  - label: "Order Items"
    name: "orders"
    label_singular: "Order Item"
    description: >
      Create order items here! Each item here will add a new item to your order page.
    folder: "content/order-items"
    create: true
    fields:
      - {
          label: "Value",
          name: "title",
          widget: "string",
          hint: "Name of the item in database",
        }
      - {
          label: "Label",
          name: "label",
          widget: "string",
          hint: "Name of the item to be displayed",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "Item description, eg: Plant based gyro with harissa, tzatiziki, marinated cucumbers, tomatoes and onions all on a folded pita",
        }
      - {
          label: "Price",
          name: "price",
          widget: "number",
          hint: "Enter a number",
        }
      - {
          label: "Serves",
          name: "serves",
          widget: "number",
          hint: "Enter a number",
        }
      - {
          label: "Position",
          name: "position",
          widget: "number",
          hint: "Where you'd like this item positioned",
        }
